# Generated by Django 5.1.6 on 2025-05-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='restaurant_images/default_image.jpg', upload_to='restaurant_images/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=models.CharField(default='restaurant_images/default_image.jpg', max_length=255),
            preserve_default=False,
        ),
    ]
