# Generated by Django 5.1.6 on 2025-05-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_dish_dishcategory_alter_cartitem_dish_dish_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dishcategory',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
