# Generated by Django 5.1.6 on 2025-05-05 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_dishcategory_description_dishcategory_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dishcategory',
            name='icon',
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING_DELIVERY', 'Pending Delivery'), ('PAID', 'Paid'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='products.order')),
            ],
        ),
    ]
